### ISSUE TITLE
Thrive lightbox via iFrame

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fancybox-for-wordpress#29]
I set everything up as explained. I added the Custom Java to the sliders section as directed. I added a click button as seen above in the link. I set taglink and made the attribute fancybox. When the button is clicked all I get is a white square with an X to close it and it does not call the link.

*NOTE: I presently have this set up as a direct link which is not ideal but the FancyBox plugin isn’t calling my lightbox url into the iFrame with your code.

Here is the Lightbox link itself:
https://selectgcr.com/?tcb_lightbox=select-gcr-pro-lightbox

**Comment by giucu91** [comment]
Should be fixed in 3.1.8
