### ISSUE TITLE
Breaks on query strings

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fancybox-for-wordpress#30]
The JavaScript regex pattern on fancybox.php:235 breaks on query strings added by W3 Total Cache.

\.(jpe?g|png|gif|bmp)$

will not match http://example.com/wp-content/uploads/image.jpg?x12345

while the following does:

\.(jpe?g|png|gif|bmp)\?.+$

**Comment by cristianraiber** [comment]
See this post for more details: https://wordpress.org/support/topic/breaks-on-query-strings/

**Comment by razvanaldea89** [comment]
fixed in new version
