### ISSUE TITLE
Undefined index PHP

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fancybox-for-wordpress#31]
Thanks for the plugin, it always does a great job.

Could you please fix the code the get rid of this notice
PHP Notice: Undefined index: extraCallsData in /wp-content/plugins/fancybox-for-wordpress/lib/admin-tab-calls.php on line 23

**Comment by razvanaldea89** [comment]
There is no more admin-tab-calls file. Notice fixed in new version
