### ISSUE TITLE
Title displays too long

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fancybox-for-wordpress#34]
If the title is longer than one line it wraps as separate paragraphs, rather than a sentence.
http://www.mnvphotography.com/galleries/night-sky-images/ 8th image down, “Crater Lake Star Trails” is the image title I am having problems with.
I am not sure how to get the text closer together, in order to be seen without scrolling down.
Thanks

**Comment by cristianraiber** [comment]
See more, here: https://wordpress.org/support/topic/title-displays-too-long/

**Comment by razvanaldea89** [comment]
fixed in new version
