### ISSUE TITLE
Stop fancybox affecting my Envira gallery

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fancybox-for-wordpress#35]
Hi there, I am using Envira Gallery. I want to keep using fancybox for normal images, and also blog images etc, but it’s also automatically opening on my Envira gallery page. Is there a way to turn it off for certain divs or pages, or even images with specific classes, so I don’t get two lightboxes opening? Cheers

**Comment by razvanaldea89** [comment]
putting nolightbox class to image or link stops the fancybox lightbox

**Comment by giucu91** [comment]
Fixed in 3.1.7
