### ISSUE TITLE
padding issue

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/fancybox-for-wordpress#45]
Issue with padding after update.
Below are 2 screenshots of an image produced by version 3.0.14 and the same image produced by version 3.1.6 (in this order). 
![screen1](https://user-images.githubusercontent.com/26008574/49736045-b2802480-fc91-11e8-9a1d-4f5ee0ea4e2f.png)
![screen2](https://user-images.githubusercontent.com/26008574/49736042-b2802480-fc91-11e8-8815-0991e23ccb9d.png)

They both have the same settings:
![screen3](https://user-images.githubusercontent.com/26008574/49736069-c75cb800-fc91-11e8-88e8-223fbf238289.png)

**Comment by mplusb** [comment]
The display of the html “title” attribute on the tag used to show in the bottom border of the picture (v3.0.14 & earlier). Now, it appears greyed out just below the border. View this page: https://www.azaleas.org/view-azalea/?id=406#gallery-1. The caption ‘Allison Ann’, Photo (c) Carolyn Beck, used to appear on the white border at the bottom of the picture (expanded to contain the title), in black text. Now is appears mostly below the border in greyed out text.

**Comment by giucu91** [comment]
fixed in 3.2.2
