### ISSUE TITLE
 Click to Hide on Overlay only works with Images

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/fancybox-for-wordpress#46]
Feedback:

Due to how this is internally hard coded, after I set HideOnOverlayClick it has no effect.

`clickSlide: <?php echo ( isset( $mfbfw['hideOnOverlayClick'] ) && $mfbfw['hideOnOverlayClick'] ? 'function(current, event) {return current.type === "image" ? "close" : false;}' : 'false' ) ?>,`

This won’t be true unless it’s an image, and I’m using this as a popup showing a DIV, so I cannot use this setting.

**Comment by giucu91** [comment]
Fixed in 3.1.6
