### ISSUE TITLE
 IE css styles are missing

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/fancybox-for-wordpress#50]
Accidentally, I discovered a missing CSS file in the repository for IE css styles, which results in a HTTP 404 and most probably displaying issues when using Internet Explorer as browser. Probably, the file needs only to be added to the repo to fix this issue.

Issue
=====
You register a specific IE css style in
fancybox.php:171, but the file is not present.

wp_register_style( 'fancybox-ie', FBFW_URL . 'assets/css/fancybox.ie.css', array( 'fancybox' ), '1.3.4' ); // Main Fancybox style fixes for IE6-8

Solution
========
Please add the missing css file to the repo.

https://wordpress.org/support/topic/ie-css-styles-are-missing/#post-11130653

**Comment by razvanaldea89** [comment]
Taking in consideration that IE 6-8 aren't supported anymore, think we should remove this

**Comment by cristianraiber** [comment]
I have to agree with @razvanaldea89 's POV. Even Microsoft isn't supporting IE anymore (being slowly replaced by Edge, which is also being re-worked on the same engine as Chrome).
