### ISSUE TITLE
 Error: property ‘title’ of undefined

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/fancybox-for-wordpress#64]
On newer jQuery, the plugin may not work – it relies on jQuery().context (looking for .title there) which has been deprecated and removed. The JavaScript error that occurs is “can’t access property ‘title’ of undefined”.

To get it to work, you’ll need to edit fancybox.php and replace “jQuery(this).context.title” with “document.title”. It’s a bandaid, but it worked for me.

**Comment by razvanaldea89** [comment]
Going to close this as it is already deployed
