### ISSUE TITLE
 Show title and drag

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/fancybox-for-wordpress#66]
1.
I’m not sure what’s intended and what’s not, but:
when an image html element contains ‘title’ field, the following html gets generated by the plugin for the title:

<div class="fancybox-custom-caption inside-caption">
<p class="caption-title">title</p></div>

and setting “show title” setting “off” doesn’t hide it, because selector in the plugin code seems to be irrelevant:
( isset( $mfbfw['titleShow'] ) ? ... : 'div.fancybox-caption p.caption-title{display:none}div.fancybox-caption{display:none;}' ) . '

2. For some reason content (image) vertical panning (drag) seems enabled and when the content gets dragged, the lightbox ‘style=”…height=’ grows on each drag, leaving permanent whitespace above title. When the entire viewport gets resized, lightbox size resets back close to normal.

**Comment by kivig2** [comment]
Git probably cut the code. The title html above:
\<div class="fancybox-custom-caption inside-caption">
\<p class="caption-title">title</p></div>

**Comment by razvanaldea89** [comment]
Going to close this as it is already deployed
