### ISSUE TITLE
 Zoom In On Image

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/fancybox-for-wordpress#78]
want to zoom-in on images in the light box by clicking the boxed image.

The + icon cursor should show when hovering over the image to indicate clicking it will zoom-in. I see this in other FancyBox implementations, but don’t see an option for this in the settings.

I see a magnifying glass in the toolbar which does zoom-in on the image, however, I’d like the zoom-in to also work on clicking the boxed image. 

For example in the first demo here:
https://fancyapps.com/fancybox/3/

https://wordpress.org/support/topic/zoom-in-on-image/

**Comment by giucu91** [comment]
added in 3.2.9
