### ISSUE TITLE
 nextgen title and description for fancybox text

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/fancybox-for-wordpress#80]
ive been trying to get the fancybox text that appears below the image to show both the title and the text of the nextgen gallery image but im unsure how.

i have this in the backend of nextgen https://i.imgur.com/YDDgThj.png
but it displays like this on the frontend https://i.imgur.com/FnxjFmI.jpg

i want the description to also be displayed underneath the title.
is this possible?

https://wordpress.org/support/topic/nextgen-title-and-description-for-fancybox-text/

**Comment by cristianraiber** [comment]
Not possible. NextGen should fix their gallery.
