### ISSUE TITLE
Border will not fully cover the image if we set the padding to the maximum size

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/fancybox-for-wordpress#86]
If we  set the padding to it's maximum size the border will not cover the full image : https://drive.google.com/file/d/1KNpzYnuxUz5EuCoVPz89qeKbDlNXG-6c/view

Tested with WP 5.6

**Comment by Florin415** [comment]
Tested with WP 5.6

**Comment by giucu91** [comment]
fixedd in 3.3.3
